- name: Setup Virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ virtualenv_path }}/requirements.txt

- name: Set permissions on migrate.py
  file: dest={{ virtualenv_path }}/vagranttest/manage.py mode=755


- name: Django migrate
  django_manage: command=migrate app_path={{ virtualenv_path }}/vagranttest virtualenv={{ virtualenv_path }}
